default: &default
  adapter: mysql2
  encoding: utf8
  pool: 50
  username: root
  password: 

production:
  <<: *default
  database: ricknmorty

development:
  <<: *default
  database: ricknmorty_dev

test:
  <<: *default
  database: ricknmorty_test